/*
  # Create Template Books Schema

  ## Overview
  This migration creates the database structure for template-based personalized books.
  The "When I Grow Up" template features 24 pages showcasing different professions
  that can be customized with a child's name, photos, and personal details.

  ## New Tables

  ### 1. `templates`
  Stores different book template types (e.g., "When I Grow Up", future templates)
  - `id` (uuid, primary key) - Unique template identifier
  - `name` (text, unique) - Template name (e.g., "When {name} Grows Up")
  - `description` (text) - Template description
  - `total_pages` (integer) - Number of pages in template
  - `created_at` (timestamptz) - Creation timestamp
  - `updated_at` (timestamptz) - Last update timestamp

  ### 2. `template_pages`
  Stores individual pages for each template with profession details
  - `id` (uuid, primary key) - Unique page identifier
  - `template_id` (uuid, foreign key) - Reference to parent template
  - `page_number` (integer) - Page sequence number
  - `profession_title` (text) - Profession name (e.g., "ASTRONAUT", "DOCTOR")
  - `text_template` (text) - Story text with {name} placeholders
  - `image_prompt_template` (text) - AI image generation prompt template
  - `created_at` (timestamptz) - Creation timestamp

  ### 3. `user_template_books`
  Stores books generated by users from templates
  - `id` (uuid, primary key) - Unique book identifier
  - `template_id` (uuid, foreign key) - Reference to template used
  - `child_name` (text) - Child's name for personalization
  - `child_gender` (text) - Child's gender
  - `child_age` (integer) - Child's age
  - `photo_url_1` (text) - URL to first uploaded photo
  - `photo_url_2` (text) - URL to second uploaded photo
  - `photo_url_3` (text) - URL to third uploaded photo
  - `generated_pages` (jsonb) - Complete generated book data
  - `pdf_url` (text) - URL to generated PDF (if stored)
  - `created_at` (timestamptz) - Creation timestamp
  - `updated_at` (timestamptz) - Last update timestamp

  ## Security
  - Enable RLS on all tables
  - For MVP: Allow public read access to templates (they are reusable content)
  - Restrict user_template_books to authenticated users only (future auth)

  ## Indexes
  - Index on template_id for faster page lookups
  - Index on page_number for ordered retrieval
*/

-- Create templates table
CREATE TABLE IF NOT EXISTS templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text UNIQUE NOT NULL,
  description text NOT NULL,
  total_pages integer NOT NULL DEFAULT 24,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create template_pages table
CREATE TABLE IF NOT EXISTS template_pages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL REFERENCES templates(id) ON DELETE CASCADE,
  page_number integer NOT NULL,
  profession_title text NOT NULL,
  text_template text NOT NULL,
  image_prompt_template text NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE(template_id, page_number)
);

-- Create user_template_books table
CREATE TABLE IF NOT EXISTS user_template_books (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL REFERENCES templates(id) ON DELETE RESTRICT,
  child_name text NOT NULL,
  child_gender text NOT NULL,
  child_age integer NOT NULL,
  photo_url_1 text,
  photo_url_2 text,
  photo_url_3 text,
  generated_pages jsonb,
  pdf_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_template_pages_template_id ON template_pages(template_id);
CREATE INDEX IF NOT EXISTS idx_template_pages_page_number ON template_pages(template_id, page_number);
CREATE INDEX IF NOT EXISTS idx_user_books_template_id ON user_template_books(template_id);
CREATE INDEX IF NOT EXISTS idx_user_books_created_at ON user_template_books(created_at DESC);

-- Enable Row Level Security
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE template_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_template_books ENABLE ROW LEVEL SECURITY;

-- RLS Policies for templates (public read access)
CREATE POLICY "Anyone can view templates"
  ON templates FOR SELECT
  USING (true);

-- RLS Policies for template_pages (public read access)
CREATE POLICY "Anyone can view template pages"
  ON template_pages FOR SELECT
  USING (true);

-- RLS Policies for user_template_books (public for MVP, can be restricted later)
CREATE POLICY "Anyone can view their books"
  ON user_template_books FOR SELECT
  USING (true);

CREATE POLICY "Anyone can create books"
  ON user_template_books FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Anyone can update their books"
  ON user_template_books FOR UPDATE
  USING (true)
  WITH CHECK (true);
