/*
  # Update template cover images and image prompts

  1. Modified Tables
    - `templates`
      - Updated cover_image URLs for all 5 templates to use verified Pexels photos
      - Updated name for Cricket template to use standard dash
    - `template_pages`
      - Updated image_prompt_template for all pages across all 5 templates
        with more detailed, descriptive prompts for better AI image generation

  2. Changes Summary
    - When I Grow Up: New cover (children in astronaut costumes, Pexels #5560536)
    - Snow White: New cover (children wearing costume, Pexels #8501420)
    - Cricket Champion: New cover (boys playing cricket, Pexels #3718433), fixed name dash
    - Cinderella: New cover (child in costume, Pexels #5560517)
    - Sports Day: New cover (children outdoor sports play, Pexels #8035133)
    - All templates: Enhanced image prompts with "Detailed watercolor/children's book illustration" prefix,
      explicit "no text" suffix, and richer scene descriptions for better AI generation quality

  3. Important Notes
    - No data is deleted or dropped
    - Only cover_image and image_prompt_template columns are updated
    - Template text_template content remains unchanged in the database
*/

-- Update cover images for all 5 templates
UPDATE templates
SET cover_image = 'https://images.pexels.com/photos/5560536/pexels-photo-5560536.jpeg?auto=compress&cs=tinysrgb&w=800'
WHERE id = 'a1111111-1111-1111-1111-111111111111';

UPDATE templates
SET cover_image = 'https://images.pexels.com/photos/8501420/pexels-photo-8501420.jpeg?auto=compress&cs=tinysrgb&w=800'
WHERE id = 'a2222222-2222-2222-2222-222222222222';

UPDATE templates
SET cover_image = 'https://images.pexels.com/photos/3718433/pexels-photo-3718433.jpeg?auto=compress&cs=tinysrgb&w=800',
    name = 'Cricket Champion - Mastering Every Shot'
WHERE id = 'a3333333-3333-3333-3333-333333333333';

UPDATE templates
SET cover_image = 'https://images.pexels.com/photos/5560517/pexels-photo-5560517.jpeg?auto=compress&cs=tinysrgb&w=800'
WHERE id = 'a4444444-4444-4444-4444-444444444444';

UPDATE templates
SET cover_image = 'https://images.pexels.com/photos/8035133/pexels-photo-8035133.jpeg?auto=compress&cs=tinysrgb&w=800'
WHERE id = 'a5555555-5555-5555-5555-555555555555';

-- Update image prompts for When I Grow Up (template a1111111)
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a cheerful {age}-year-old {gender} child named {name} wearing a bright white spacesuit with a round glass helmet, floating weightlessly in outer space. Colorful planets, swirling nebulae, and twinkling stars surround {name}. Earth glows blue below. Soft brush strokes, warm pastel palette, whimsical storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 1;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a caring {age}-year-old {gender} child named {name} in a crisp white doctor''s coat and a shiny silver stethoscope, standing in a cheerful hospital room with colorful wall art. {name} holds a clipboard and smiles warmly at a plush teddy bear patient on the bed. Soft pastel tones, gentle lighting, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 2;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a {age}-year-old {gender} child named {name} standing confidently at a colorful classroom chalkboard with ABCs and numbers, holding an open storybook. Small students sit on a rainbow rug listening eagerly. Bright classroom with bookshelves, globe, and hanging art. Warm sunny lighting, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 3;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a brave {age}-year-old {gender} child named {name} wearing a shiny red firefighter helmet and yellow turnout coat, standing proudly next to a bright red fire truck with a golden ladder. A Dalmatian dog sits beside {name}. Blue sky, neighborhood houses in background. Bold warm colors, heroic mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 4;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a joyful {age}-year-old {gender} child named {name} wearing a tall white chef''s hat and apron, stirring a big pot in a warm kitchen. Fresh vegetables, colorful fruits, stacked cupcakes, and a rising cake surround {name}. Steam wisps, copper pots on shelves, checkered tiles. Cozy warm tones, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 5;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: an adventurous {age}-year-old {gender} child named {name} in a navy pilot''s uniform with gold wings badge and cap, sitting in an airplane cockpit filled with dials and instruments. Through the wide windshield, fluffy clouds and a golden sunset stretch endlessly. Exciting aviation mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 6;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a gentle {age}-year-old {gender} child named {name} in a light blue vet coat, carefully examining a fluffy golden puppy with a tiny stethoscope. A kitten, bunny, and parrot watch nearby on the clinic counter. Bright, clean veterinary office with paw-print posters. Soft warm colors, caring mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 7;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a creative {age}-year-old {gender} child named {name} in a paint-splattered smock, standing at a tall wooden easel, painting a vibrant rainbow landscape. Color palettes, jars of brushes, and splashes of paint fill a sunlit art studio. Canvases lean against walls. Vivid joyful colors, creative atmosphere, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 8;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: an excited {age}-year-old {gender} child named {name} wearing a white lab coat and big safety goggles, holding a bubbling test tube that glows green. A microscope, beakers with colorful liquids, and a model of the solar system fill the science lab. Bright discovery mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 9;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a passionate {age}-year-old {gender} child named {name} playing a shiny acoustic guitar on a small wooden stage, colorful musical notes floating and dancing in the air around {name}. A soft warm spotlight shines down, audience silhouettes clap. Joyful concert atmosphere, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 10;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: an energetic {age}-year-old {gender} child named {name} in bright athletic sportswear, mid-stride on a running track with arms pumping. A stadium with cheering crowd, colorful banners, and a finish line ribbon ahead. Dynamic action pose, motion lines, triumphant mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 11;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a thoughtful {age}-year-old {gender} child named {name} wearing a bright yellow hard hat and orange safety vest, studying a large blueprint on a table. Behind {name}, a model bridge and tower made of colorful blocks rise up. Construction cranes and buildings in the background under a blue sky. Innovative mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 12;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a friendly {age}-year-old {gender} child named {name} in light blue dentist scrubs, holding a giant toothbrush next to a big smiling tooth character. A bright dental office with a colorful chart of teeth on the wall. Clean, cheerful medical environment, reassuring friendly mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 13;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a happy {age}-year-old {gender} child named {name} wearing denim overalls and a wide straw hat, standing in a lush vegetable garden holding a basket overflowing with tomatoes and carrots. A red barn, grazing cows, and rolling green hills under a warm golden sunrise. Peaceful rural mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 14;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a strong {age}-year-old {gender} child named {name} wearing a hard hat, safety vest, and sturdy boots, holding a hammer near wooden beams of a house frame. Other friendly construction workers wave in the background. Bright sunny construction site, teamwork mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 15;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a warm {age}-year-old {gender} child named {name} sitting in a cozy library corner surrounded by tall bookshelves packed with colorful books, reading aloud from a large open storybook to a circle of attentive young listeners. Soft golden lamp light, comfortable reading chairs, inviting atmosphere, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 16;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: an artistic {age}-year-old {gender} child named {name} holding a vintage camera up to one eye, capturing a beautiful butterfly landing on a sunflower in a meadow. Framed photos float around showing mountains, animals, and sunsets. Warm golden hour lighting, creative mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 17;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a caring {age}-year-old {gender} child named {name} in khaki zoo keeper uniform and wide-brimmed hat, gently feeding a tall giraffe that bends down to eat from {name}''s hand. A baby elephant and colorful parrots are nearby. Lush green zoo habitat with trees and pond. Gentle caring mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 18;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a graceful {age}-year-old {gender} child named {name} in a sparkling dance outfit, performing an elegant leap across a grand stage with deep red velvet curtains and warm stage lights. Sparkles trail behind {name}''s movement. Audience silhouettes below. Elegant theatrical mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 19;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a cheerful {age}-year-old {gender} child named {name} in a blue postal uniform with a cap, carrying a leather mail bag full of colorful letters and packages, walking along a friendly neighborhood street with painted mailboxes, white picket fences, and blooming flower gardens. Bright sunny day, community mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 20;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: an adventurous {age}-year-old {gender} child named {name} in a blue wetsuit and snorkel mask, swimming underwater surrounded by a friendly dolphin, a sea turtle, colorful coral reefs, and schools of tropical fish. Sunlight rays pierce through the crystal blue water. Magical ocean mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 21;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a proud {age}-year-old {gender} child named {name} in a park ranger uniform with a wide flat hat and bronze badge, standing on a forest trail with towering pine trees. A deer peeks from behind a tree, an owl sits on a branch, and wildflowers bloom along the path. Peaceful nature mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 22;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a delighted {age}-year-old {gender} child named {name} in a white baker''s apron and puffy hat, holding a tray of freshly baked golden cookies in a cozy bakery. Glass display cases show layered cakes, braided bread, and pastries. Flour dust floats in warm oven light. Cozy delicious mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 23;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor children''s book illustration: a confident {age}-year-old {gender} child named {name} standing on a hilltop at golden sunrise, looking toward a bright horizon. Floating around {name} are soft glowing symbols of different careers: a stethoscope, paintbrush, rocket, book, musical note, chef hat, and magnifying glass. Dreamy hopeful atmosphere, endless possibilities mood, storybook style, no text.' WHERE template_id = 'a1111111-1111-1111-1111-111111111111' AND page_number = 24;

-- Update image prompts for Snow White (template a2222222)
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a {age}-year-old {gender} child named {name} in simple patched clothes, carrying a heavy wicker basket through a grand stone castle kitchen. Two elaborately dressed sisters point and snicker while a stern stepmother watches from a throne-like chair. Warm candlelight, cobblestone floor, copper pots hanging on walls. Classic storybook style, no text.' WHERE template_id = 'a2222222-2222-2222-2222-222222222222' AND page_number = 1;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a {age}-year-old {gender} child named {name} sitting on a stone castle windowsill, smiling softly while feeding colorful songbirds from open palm. Morning sunlight streams through the arched window. Two sisters frown in the shadowy background. Soft pastel colors, gentle atmosphere, classic storybook style, no text.' WHERE template_id = 'a2222222-2222-2222-2222-222222222222' AND page_number = 2;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a {age}-year-old {gender} child named {name} walking along a winding path into a tall ancient forest. Golden rays of sunlight filter through the canopy. A rabbit peeks from behind ferns, a bluebird perches on a branch overhead. The mood shifts from sadness to quiet hope. Rich greens, dappled light, classic storybook style, no text.' WHERE template_id = 'a2222222-2222-2222-2222-222222222222' AND page_number = 3;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a charming thatched-roof cottage nestled among tall forest trees with a mushroom-lined path leading to the door. Inside, a {age}-year-old {gender} child named {name} sweeps the wooden floor while sunlight pours through small round windows. Seven tiny chairs, seven tiny beds, cozy hearth. Warm golden tones, classic storybook style, no text.' WHERE template_id = 'a2222222-2222-2222-2222-222222222222' AND page_number = 4;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a {age}-year-old {gender} child named {name} sitting at a small round wooden table surrounded by seven cheerful dwarfs of different heights and personalities, all sharing a warm meal. Cozy candlelight, wooden beams overhead, a crackling fireplace. Everyone smiles kindly. Warm amber tones, classic storybook style, no text.' WHERE template_id = 'a2222222-2222-2222-2222-222222222222' AND page_number = 5;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a cloaked old woman with hidden eyes offers a single gleaming red apple to a {age}-year-old {gender} child named {name} at the cottage door. The apple glows ominously. Shadows creep at the edges while the cottage remains warm. Subtle tension, rich deep colors, classic storybook style, no text.' WHERE template_id = 'a2222222-2222-2222-2222-222222222222' AND page_number = 6;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a crystal glass coffin resting on a flower-covered hilltop under a canopy of blossoming trees. A {age}-year-old {gender} child named {name} lies peacefully inside with folded hands. Seven dwarfs weep nearby while forest animals gather in a circle. Tender bittersweet mood, soft light, classic storybook style, no text.' WHERE template_id = 'a2222222-2222-2222-2222-222222222222' AND page_number = 7;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a gentle young prince on a white horse arriving at the glass coffin on the hilltop. A {age}-year-old {gender} child named {name} begins to stir awake, eyes fluttering open. Dwarfs look up in astonished hope, golden sunlight breaking through clouds. Magical moment, bright hopeful colors, classic storybook style, no text.' WHERE template_id = 'a2222222-2222-2222-2222-222222222222' AND page_number = 8;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a {age}-year-old {gender} child named {name} standing between the kind prince and the seven dwarfs, holding a dwarf''s hand in farewell. A winding forest path leads to a sunlit white castle on a distant hill. Warm hopeful atmosphere, golden hour lighting, classic storybook style, no text.' WHERE template_id = 'a2222222-2222-2222-2222-222222222222' AND page_number = 9;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a grand castle courtyard celebration with banners and flowers. A {age}-year-old {gender} child named {name} in beautiful royal clothes stands at the center, surrounded by the prince, the seven dwarfs visiting, and new friends all smiling. Warm golden sunlight, joyful atmosphere, classic storybook happily-ever-after ending, no text.' WHERE template_id = 'a2222222-2222-2222-2222-222222222222' AND page_number = 10;

-- Update image prompts for Cricket Champion (template a3333333)
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} in crisp white cricket gear and blue helmet, executing a textbook forward defensive shot on a sunlit cricket ground. Front foot planted forward, bat perfectly straight next to the front pad, head still and eyes watching the ball. Green pitch, white crease lines, clear blue sky. Clean coaching-diagram style, no text.' WHERE template_id = 'a3333333-3333-3333-3333-333333333333' AND page_number = 1;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} in cricket whites and helmet, executing a beautiful straight drive. Front knee bent, bat following through in a full arc toward the sightscreen, head perfectly over the ball. The ball races along the green pitch toward the boundary. Sunny cricket ground, clear coaching illustration, no text.' WHERE template_id = 'a3333333-3333-3333-3333-333333333333' AND page_number = 2;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} playing an elegant cover drive, front foot reaching toward off side, bat sweeping through in a graceful high arc. The ball flies through the cover region between fielders. Beautiful side-on stance, arms extended. Lush green cricket field, classic coaching pose, no text.' WHERE template_id = 'a3333333-3333-3333-3333-333333333333' AND page_number = 3;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} in cricket gear playing a controlled on drive. Front foot angled toward mid-on, bat face straight, wrists firm. Ball glides past the bowler on the leg side. Balanced stance with weight transferred forward. Clean green pitch, coaching-style illustration, no text.' WHERE template_id = 'a3333333-3333-3333-3333-333333333333' AND page_number = 4;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} in cricket whites and helmet, executing a powerful pull shot. Body rotating on the back foot, bat swinging horizontally, front leg lifting slightly. The ball rockets toward mid-wicket. Dynamic action pose with motion energy. Sunny cricket ground, coaching-style illustration, no text.' WHERE template_id = 'a3333333-3333-3333-3333-333333333333' AND page_number = 5;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} executing a crisp square cut shot. Back foot planted across toward off stump, body opening slightly, bat slicing horizontally through the ball toward the point boundary. Head perfectly still. Cricket field with fielders in background, coaching-style illustration, no text.' WHERE template_id = 'a3333333-3333-3333-3333-333333333333' AND page_number = 6;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} in cricket whites playing a classic sweep shot against a spin bowler. Front knee down on the pitch, back leg folded, bat sweeping in a low arc in front of the body. Head leaning forward over the ball. Spinner visible in the background. Clean coaching-style illustration, no text.' WHERE template_id = 'a3333333-3333-3333-3333-333333333333' AND page_number = 7;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} playing a confident lofted drive. Front foot firmly planted, bat following through high above the shoulder, ball soaring over the infield toward the boundary. Stable lower body, eyes following the ball. Blue sky, green outfield, coaching-style illustration, no text.' WHERE template_id = 'a3333333-3333-3333-3333-333333333333' AND page_number = 8;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} in cricket gear playing a solid back-foot defensive shot. Back foot planted on the crease line, bat straight and close to the pads, ball dropping gently near the feet. Composed posture, soft hands. Cricket pitch with stumps visible, coaching-style illustration, no text.' WHERE template_id = 'a3333333-3333-3333-3333-333333333333' AND page_number = 9;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} executing a delicate late cut shot. Bat angled with soft wrists, body slightly open, ball guided past the slip fielders toward third man. Wicket-keeper reaching behind, slips watching. Precise timing captured in a still moment. Cricket ground setting, coaching-style illustration, no text.' WHERE template_id = 'a3333333-3333-3333-3333-333333333333' AND page_number = 10;

-- Update image prompts for Cinderella (template a4444444)
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a {age}-year-old {gender} child named {name} in simple worn clothes, scrubbing a large wooden table in a grand old kitchen. Two overdressed stepsisters lounge on cushioned chairs pointing, while a stern stepmother supervises from the doorway. Warm but melancholy firelight, stone walls, hanging herbs. Classic storybook style, no text.' WHERE template_id = 'a4444444-4444-4444-4444-444444444444' AND page_number = 1;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a {age}-year-old {gender} child named {name} sitting curled up on a small stool beside a crackling fireplace, chin resting on knees, gazing into the dancing orange flames. Soft embers float upward like tiny stars. An old broom and bucket rest nearby. Warm amber glow, dreamy peaceful atmosphere, classic storybook style, no text.' WHERE template_id = 'a4444444-4444-4444-4444-444444444444' AND page_number = 2;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a royal messenger in a plumed hat presenting a golden scroll at the door. Two excited stepsisters twirl in half-finished ball gowns. A {age}-year-old {gender} child named {name} stands in the background holding a simple apron, looking hopeful but sad. Stern stepmother blocks the way. Rich colors, classic storybook style, no text.' WHERE template_id = 'a4444444-4444-4444-4444-444444444444' AND page_number = 3;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a glowing fairy godmother in a flowing silver gown, holding a sparkling wand, appearing in a moonlit garden before a {age}-year-old {gender} child named {name} who looks up in wonder. A pumpkin sits on the garden path, mice peek from behind flower pots. Magical blue and gold light radiates outward. Classic storybook style, no text.' WHERE template_id = 'a4444444-4444-4444-4444-444444444444' AND page_number = 4;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a {age}-year-old {gender} child named {name} spinning joyfully as rags transform into a magnificent glittering outfit with glass slippers that catch the moonlight. Behind, a pumpkin morphs into a golden carriage, mice transform into elegant white horses. Sparkles and fairy dust fill the air. Magical transformation scene, classic storybook style, no text.' WHERE template_id = 'a4444444-4444-4444-4444-444444444444' AND page_number = 5;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a grand palace ballroom with crystal chandeliers, marble columns, and elegantly dressed guests. A {age}-year-old {gender} child named {name} in a magnificent outfit dances gracefully with a kind young prince at the center of the room. Golden candlelight reflects off the polished floor. Enchanting atmosphere, classic storybook style, no text.' WHERE template_id = 'a4444444-4444-4444-4444-444444444444' AND page_number = 6;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a {age}-year-old {gender} child named {name} running down wide marble palace stairs under a midnight sky full of stars. One sparkling glass slipper sits on a step behind. A large clock tower in the background shows midnight. Outfit beginning to shimmer and fade. Dramatic but child-friendly urgency, classic storybook style, no text.' WHERE template_id = 'a4444444-4444-4444-4444-444444444444' AND page_number = 7;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a determined young prince traveling through a village in a horse-drawn carriage, holding up a single sparkling glass slipper on a velvet cushion. Villagers peer out from doorways and windows. Cobblestone streets, thatched-roof cottages, bright daytime scene. Hopeful atmosphere, classic storybook style, no text.' WHERE template_id = 'a4444444-4444-4444-4444-444444444444' AND page_number = 8;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: inside a modest room, the prince kneels to place the glass slipper on a {age}-year-old {gender} child named {name}''s foot. The slipper glows as it fits perfectly. Two stepsisters and the stepmother look shocked and dismayed in the background. Warm hopeful golden light fills the room, classic storybook style, no text.' WHERE template_id = 'a4444444-4444-4444-4444-444444444444' AND page_number = 9;
UPDATE template_pages SET image_prompt_template = 'Detailed watercolor fairy-tale illustration: a beautiful palace garden with fountains, rose bushes, and butterflies. A {age}-year-old {gender} child named {name} in elegant royal attire walks happily with the prince and new friends through the garden. Bright blue sky, warm sunshine, flowers in full bloom. Peaceful joyful fairy-tale ending, classic storybook style, no text.' WHERE template_id = 'a4444444-4444-4444-4444-444444444444' AND page_number = 10;

-- Update image prompts for Sports Day (template a5555555)
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a determined {age}-year-old {gender} child named {name} in bright athletic clothes and running shoes, sprinting on a red school track. Arms pumping, knees lifting high, hair flowing. A cheering crowd of parents and students behind a colorful Sports Day banner. Bright sunny day, dynamic motion, no text.' WHERE template_id = 'a5555555-5555-5555-5555-555555555555' AND page_number = 1;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: an agile {age}-year-old {gender} child named {name} dribbling a black-and-white football past two defenders on a lush green school field. Eyes focused on the ball, legs in dynamic motion. White goalposts visible ahead, teammates cheering from the sideline. Bright energetic atmosphere, no text.' WHERE template_id = 'a5555555-5555-5555-5555-555555555555' AND page_number = 2;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a focused {age}-year-old {gender} child named {name} in a basketball jersey, shooting a basketball toward an orange hoop. Knees bent, arms fully extended, the ball at the peak of its arc. Indoor school gymnasium with polished wooden floor, colorful bleachers, bright overhead lights, no text.' WHERE template_id = 'a5555555-5555-5555-5555-555555555555' AND page_number = 3;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: an athletic {age}-year-old {gender} child named {name} on a green tennis court, hitting a forehand with perfect form. Side-on stance, racket following through high, tennis ball crossing the white net. Sunny outdoor court with green trees in the background. Clean sporty atmosphere, no text.' WHERE template_id = 'a5555555-5555-5555-5555-555555555555' AND page_number = 4;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a streamlined {age}-year-old {gender} child named {name} in a swim cap and goggles, gliding through crystal-clear blue pool water in a freestyle stroke. Face turning to the side to breathe, water splashing gently. Lane lines and pool tiles visible. Bright indoor pool lighting, refreshing atmosphere, no text.' WHERE template_id = 'a5555555-5555-5555-5555-555555555555' AND page_number = 5;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a graceful {age}-year-old {gender} child named {name} in a gymnastics leotard, walking along a balance beam with arms extended for balance. Focused determined expression. Safety mats below, a supportive coach watching nearby. Bright gym with colorful equipment in background, no text.' WHERE template_id = 'a5555555-5555-5555-5555-555555555555' AND page_number = 6;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a nimble {age}-year-old {gender} child named {name} leaping to smash a badminton shuttlecock, racket arm stretched high overhead. Indoor court with a white net, court lines on the floor, and a competitor on the other side. Athletic jump captured mid-air. Bright indoor lighting, dynamic action, no text.' WHERE template_id = 'a5555555-5555-5555-5555-555555555555' AND page_number = 7;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} in a hockey uniform with shin guards, crouching low and dribbling a ball with a hockey stick on a green turf field. Teammates run alongside in matching jerseys. School field with goal cage visible. Determined teamwork atmosphere, no text.' WHERE template_id = 'a5555555-5555-5555-5555-555555555555' AND page_number = 8;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a {age}-year-old {gender} child named {name} captured mid-flight in a long jump, legs tucked forward, arms reaching ahead. A sand pit stretches below, a white takeoff board visible behind. Outdoor school track with spectators clapping. Sense of weightless flight and freedom, no text.' WHERE template_id = 'a5555555-5555-5555-5555-555555555555' AND page_number = 9;
UPDATE template_pages SET image_prompt_template = 'Detailed children''s book illustration: a proud {age}-year-old {gender} child named {name} standing on a winners podium wearing a shiny gold medal on a ribbon, arms raised in celebration. Scattered around the podium are a football, tennis racket, basketball, hockey stick, swim goggles, and badminton shuttlecock. Friends and family cheer, colorful confetti falls. Triumphant celebratory mood, bright storybook style, no text.' WHERE template_id = 'a5555555-5555-5555-5555-555555555555' AND page_number = 10;